openapi: 3.0.2
info:
    title: Hotel-API
    version: 1.0.0
    description: this is a swagger for my Hotel API
paths:
    /guests:
        get:
            tags:
                - guests
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of guests:
                                    value:
                                        - Pablo Gonzalez
                                        - John Man
                    description: Returns a list of all guests
            summary: Get a list of all guests
            description: |
                Returns a list of all guests
        post:
            requestBody:
                description: A new guest to be created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-guest'
                required: true
            tags:
                - new-guest
            responses:
                '201':
                    description: The guest has been successfully added
                '400':
                    description: One or all params are missing
            summary: Creates a guest
            description: Creates a new guest
    '/guests/{id}':
        get:
            tags:
                - details
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of guest:
                                    value: "    { GuestID: 1, FirstName: \"Pablo\", LastName: \"Gonzalez\", PhoneNumber: \"523456789\", EmailAddress: \"Gonzales12@gmail.com.com\" },\r\n"
                    description: Returns full details of given guest
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Guest /w+ was not found:
                                    value:
                                        error: Guest \w+ was not found in game array
                    description: Guest was not found
            operationId: id
            summary: Get full details of a guest
            description: Returns full details of the guest given
        put:
            requestBody:
                description: Update a users details
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/update-guests-details'
                required: true
            tags:
                - change-details
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    description: The updates were made successfully
                '400':
                    description: |+
                        Failed to update the guest

                '404':
                    description: No guests exist with that id
            summary: Change guests details
            description: Change guests details by id
        delete:
            tags:
                - delete-guest
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/delete-guest'
                    description: Successfully deleted the guest!
                '400':
                    description: Failed to delete the guest!
                '404':
                    description: No guest by that Id was found
            summary: Delete a guest
            description: Deletes a guest by the Id
    /rooms:
        get:
            tags:
                - Rooms
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of rooms:
                                    value: "    {id: 1, GuestId: \"1\", RoomNumber: \"40\", CheckInDate: \"December 17, 2023 08:24:00\", CheckOutDate: \"December 20, 2023 08:24:00\", Status:\"Occupied\"},\r\n    {id: 2, GuestId: \"3\", RoomNumber: \"41\", CheckInDate: \"December 19, 2023 06:24:00\", CheckOutDate: \"December 20, 2023 08:24:00\", Status:\"Occupied\"},\r\n    {id: 3, GuestId: \"4\", RoomNumber: \"42\", CheckInDate: \"December 16, 2023 01:25:00\", CheckOutDate: \"December 21, 2023 08:24:00\", Status:\"Occupied\"},\r\n    {id: 4, GuestId: \"5\", RoomNumber: \"43\", CheckInDate: \"December 15, 2023 12:24:00\", CheckOutDate: \"December 22, 2023 08:24:00\", Status:\"Occupied\"}"
                    description: Returns a list of all rooms
            summary: Get a list of all rooms
            description: |
                Returns a list of all rooms
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-room'
                        examples:
                            new room:
                                value:
                                    id: 3
                                    GuestId: '4'
                                    RoomNumber: '42'
                                    CheckInDate: 'December 16, 2023 01:25:00'
                                    CheckOutDate: 'December 21, 2023 08:24:00'
                                    Status: Occupied
                required: true
            tags:
                - new-room
            responses:
                '201':
                    description: The room has been successfully added
                '400':
                    description: One or all params are missing
            summary: Creates a Room
            description: Creates a new guest
    '/rooms/{id}':
        get:
            tags:
                - details
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of room:
                                    value: "    {id: 1, GuestId: \"1\", RoomNumber: \"40\", CheckInDate: \"December 17, 2023 08:24:00\", CheckOutDate: \"December 20, 2023 08:24:00\", Status:\"Occupied\"},\r\n"
                    description: Returns full details of given room
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value: Did not find an room with that id
                    description: Guest was not found
            summary: Gets full details of a room
            description: |
                Return full details of a room
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error Message.
        new-guest:
            title: Root Type for new-guest
            description: For adding new guests
            required:
                - PhoneNumber
                - EmailAddress
                - FirstName
                - LastName
            type: object
            properties:
                FirstName:
                    type: string
                LastName:
                    type: string
                PhoneNumber:
                    maximum: 999999999
                    minimum: 100000000
                    type: integer
                EmailAddress:
                    type: string
            example:
                FirstName: Joonas
                LastName: Oispuu
                PhoneNumber: '1234567890'
                EmailAddress: s@gmail.com
        delete-guest:
            description: Delete guest by Id
            required:
                - id
            type: object
            properties:
                id:
                    description: ''
                    type: string
            example:
                id: 1
        update-guests-details:
            description: update a guests details by their id
            type: object
            properties:
                EmailAddress:
                    description: ''
                    type: string
                FirstName:
                    description: ''
                    type: string
                LastName:
                    description: ''
                    type: string
                PhoneNumber:
                    description: ''
                    type: integer
            example:
                FirstName: Joonas
                LastName: Oispuu
                PhoneNumber: '1234567890'
                EmailAddress: s@gmail.com
        new-room:
            description: for adding new rooms
            required:
                - GuestId
                - RoomNumber
                - CheckInDate
                - CheckOutDate
                - Status
            type: object
            properties:
                GuestId:
                    description: the guests id
                    type: integer
                RoomNumber:
                    description: ''
                    type: integer
                CheckInDate:
                    description: ''
                    type: string
                    example: 'December 17, 2023 08:24:00'
                CheckOutDate:
                    description: ''
                    type: string
                    example: 'December 17, 2023 08:24:00'
                Status:
                    description: ''
                    type: string
            example:
                id: 3
                GuestId: '4'
                RoomNumber: '42'
                CheckInDate: 'December 16, 2023 01:25:00'
                CheckOutDate: 'December 21, 2023 08:24:00'
                Status: Occupied
        date:
            description: date time
            type: object
