openapi: 3.0.2
info:
    title: Hotel-API
    version: 1.0.0
    description: this is a swagger for my Hotel API
paths:
    /guests:
        get:
            tags:
                - guests
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of guests:
                                    value:
                                        - Pablo Gonzalez
                                        - John Man
                    description: Returns a list of all guests
            summary: Get a list of all guests
            description: |
                Returns a list of all guests
        post:
            requestBody:
                description: A new guest to be created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-guest'
                required: true
            tags:
                - new-guest
            responses:
                '201':
                    description: The guest has been successfully added
                '400':
                    description: One or all params are missing
            summary: Creates a guest
            description: Creates a new guest
    '/guests/{id}':
        get:
            tags:
                - details
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of guest:
                                    value: "    { GuestID: 1, FirstName: \"Pablo\", LastName: \"Gonzalez\", PhoneNumber: \"523456789\", EmailAddress: \"Gonzales12@gmail.com.com\" },\r\n"
                    description: Returns full details of given guest
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Guest /w+ was not found:
                                    value:
                                        error: Guest \w+ was not found in game array
                    description: Guest was not found
            operationId: id
            summary: Get full details of a guest
            description: Returns full details of the guest given
        put:
            requestBody:
                description: Update a users details
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/update-guests-details'
                required: true
            tags:
                - change-details
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    description: The updates were made successfully
                '400':
                    description: |+
                        Failed to update the guest

                '404':
                    description: No guests exist with that id
            summary: Change guests details
            description: Change guests details by id
        delete:
            tags:
                - delete-guest
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/delete-guest'
                    description: Successfully deleted the guest!
                '400':
                    description: Failed to delete the guest!
                '404':
                    description: No guest by that Id was found
            summary: Delete a guest
            description: Deletes a guest by the Id
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error Message.
        new-guest:
            title: Root Type for new-guest
            description: For adding new guests
            required:
                - PhoneNumber
                - EmailAddress
                - FirstName
                - LastName
            type: object
            properties:
                FirstName:
                    type: string
                LastName:
                    type: string
                PhoneNumber:
                    maximum: 999999999
                    minimum: 100000000
                    type: integer
                EmailAddress:
                    type: string
            example:
                FirstName: Joonas
                LastName: Oispuu
                PhoneNumber: '1234567890'
                EmailAddress: s@gmail.com
        delete-guest:
            description: Delete guest by Id
            required:
                - id
            type: object
            properties:
                id:
                    description: ''
                    type: string
            example:
                id: 1
        update-guests-details:
            description: update a guests details by their id
            type: object
            properties:
                EmailAddress:
                    description: ''
                    type: string
                FirstName:
                    description: ''
                    type: string
                LastName:
                    description: ''
                    type: string
                PhoneNumber:
                    description: ''
                    type: integer
            example:
                FirstName: Joonas
                LastName: Oispuu
                PhoneNumber: '1234567890'
                EmailAddress: s@gmail.com
